spring:
  application:
    name: byte-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://121.250.209.74:3306/qingxun?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&lowerCaseTableNames=1&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:cong0917}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 60000
      idle-timeout: 60000
  redis:
    host: ${REDIS_HOST:121.250.209.74}
    port: ${REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  mvc:
    async:
      request-timeout: 15000

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


enable:
  swagger: true

server:
  port: 8090

qiniu:
  accessKey: 5gDeEHZm-LaJ6Hp9n8OE9BvVtjIML4uiSCCzk7Rp
  accessSecretKey: pCVtGDSEjuL0n8Ceo7RmwoQTvSdnDNXhs1S_ed2j
