spring:
  application:
    name: byte-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.97.5:3306/qingxun?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: cong0917
  redis:
    host: 101.201.143.127
    port: 6379
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


enable:
  swagger: true

server:
  port: 8090
  servlet:
    context-path: /api

qiniu:
  accessKey: 5gDeEHZm-LaJ6Hp9n8OE9BvVtjIML4uiSCCzk7Rp
  accessSecretKey: pCVtGDSEjuL0n8Ceo7RmwoQTvSdnDNXhs1S_ed2j
